name: ci

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches-ignore: [main]
    tags-ignore: ['**']

jobs:
  lint-pr:
    if: github.event_name == 'pull_request'
    uses: nickdemianchuk/actions/.github/workflows/lint-pr.yml@main

  lint-commits:
    if: github.event_name == 'push'
    uses: nickdemianchuk/actions/.github/workflows/lint-commits.yml@main
