name: ci

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches-ignore: [main]
    tags-ignore: ['**']

jobs:
  lint-pr:
    if: github.event_name == 'pull_request'
    uses: nickdemianchuk/actions/.github/workflows/lint-pr.yml@main

  lint-commits:
    if: github.event_name == 'push'
    uses: nickdemianchuk/actions/.github/workflows/lint-commits.yml@main

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: make vet
      - run: make lint
      - run: make test
